### ISSUE TITLE
TypeError: Cannot read property 'selectedBackgroundColor' of undefined

### ISSUE THREAD

**Issue by cybersasi** [GR34SE/react-switch-selector#1]
hi I have this error after following the example in the Readme 

TypeError: Cannot read property 'selectedBackgroundColor' of undefined
SwitchSelector

src/SwitchSelector.tsx:86

**Comment by GR34SE** [comment]
Hey, thanks for reporting that issue.

It seems like your initialSelectedIndex prop doesn't match item from your options array at that index. 
I've handled this scenario in 114fd2c2acdef694199021f45a899ec30174be7d

Cheers
