### ISSUE TITLE
Per-corner borderRadius

### ISSUE THREAD

**Issue by nicolasdeory** [GR34SE/react-switch-selector#104]
I'd like to set a `border-radius` style so the wrapper has a border radius, while the inner selected option has a border radius on the outer corners, but not on the inner ones. This doesn't seem to be possible with the current exposed properties.

Here's an usage example:
![image](https://user-images.githubusercontent.com/1417708/149775095-9327275e-0e28-41fb-9749-b1b2c7e3ef07.png)

**Comment by GR34SE** [comment]
Hey! thanks for reaching out.

It should be more feasible in [v2.2.0](https://github.com/GR34SE/react-switch-selector/releases/tag/v2.2.0)

Please see the following Storybook example: https://gr34se.github.io/react-switch-selector/?path=/story/switchselector--outer-border-radius

hope that will fit your needs 🙂
