### ISSUE TITLE
Use the name attribute

### ISSUE THREAD

**Issue by Jack-Stoller** [GR34SE/react-switch-selector#124]
Adding the `name` attribute to the `SwitchSelector` component could be helpful for parsing forms.

This could just reference a hidden input within the component.

Right now it's fairly simple to do this externally, but it requires a state variable and a bit more code. 

```
const Component = () => {

    const [val, set_val] = useState(true);

    return (
        <>
              <SwitchSelector
                  options={[
                      {
                          label: "Yes",
                          value: true
                      },
                      {
                          label: "No",
                          value: false
                      }
                  ]}
                  onChange={set_val}
              />
              <input type="hidden" name="val" value={val} />
        </>
    );
}
```

Data types would be lost, but it would still be convenient to have to be integrated. This might also be helpful for adding other features in the future that would rely on an input element internally.

**Comment by GR34SE** [comment]
Hey, thanks for reaching out. v2.2.1 should do the trick

https://github.com/GR34SE/react-switch-selector/releases/tag/v2.2.1
