### ISSUE TITLE
More than one copy of React in the same app

### ISSUE THREAD

**Issue by Raveen-AJ** [GR34SE/react-switch-selector#140]
When I'm using different version of react and react-dom compared to switch-selector,  I'm getting this error. 

> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**Comment by GR34SE** [comment]
Please try with https://github.com/GR34SE/react-switch-selector/releases/tag/v2.3.0
