### ISSUE TITLE
missing space in background: at src/SwitchSelector.styled.ts

### ISSUE THREAD

**Issue by wagnerlanger** [GR34SE/react-switch-selector#156]
https://github.com/GR34SE/react-switch-selector/blob/4593bc163f948ff449230ee00aae1de840567e50/src/SwitchSelector.styled.ts#L82

when using css variables there is a problem in this line, where the variable is not rendered properly.
"solidvar(--white)"
it shoud be like
"solid var(--white)"

**Comment by GR34SE** [comment]
https://github.com/GR34SE/react-switch-selector/commit/36f54763a5681aa2b7a5c3faa5d37b6bfe742f80
