### ISSUE TITLE
Icon instead of string

### ISSUE THREAD

**Issue by mqtik** [GR34SE/react-switch-selector#22]
Is there a way to use an icon instead of a string?

**Comment by GR34SE** [comment]
Hey, 

yes - I've updated the docs and types in v1.2.1 - you can pass any HTML element or React component as a label.
https://github.com/GR34SE/react-switch-selector/releases/tag/v1.2.1

**Comment by mqtik** [comment]
That was fast. Thanks a lot 👍 !
