### ISSUE TITLE
forcedSelectedIndex doesn't work

### ISSUE THREAD

**Issue by YakimchykNadzeya** [GR34SE/react-switch-selector#80]
I set a forcedSelectedIndex value but it doesn't reset a toggle.

Only manual change of a toggle value works for me. How can I reset a toggle value in code?

**Comment by GR34SE** [comment]
Hello @YakimchykNadzeya,

I can't seem to reproduce the issue. I have deployed the storybook that lets you play around with props API: https://gr34se.github.io/react-switch-selector/

please see the given example with forcedSelectedIndex set to arbitrary value:
https://gr34se.github.io/react-switch-selector/?path=/story/switchselector--three-options&args=forcedSelectedIndex:2
